### PR TITLE
fix(local): prevent trigger from running on entire source dir

### LINKED ISSUE #208: Local file trigger moving the entire directory even if regexp is defined
### Describe the issue

Hi,
If i specify a local file trigger with move action and regExp, it's deleting/moving my source directory to the destination.
I would like to only move files thats matching the regExp to the `moveDirectory`

```yaml
id: hummingbird_809806
namespace: company.team

triggers:
  - id: watch
    type: io.kestra.plugin.fs.local.Trigger
    from: "/tmp/test/"
    regExp: "u"
    interval: PT10S
    action: MOVE
    moveDirectory: "/tmp/output/"
```

In this example, the folder "test" is just deleted (not moved) after every execution and that resulting in this error:

```bash
12:59:32.335 WARN  worker_332   flow.hummingbird_809806.watch [tenant: main] [namespace: company.team] [flow: hummingbird_809806] [trigger: watch] [date: 2025-07-13T12:59:31.380Z] Trigger evaluation failed in the worker with error: Source path does not exist: /tmp/test
java.lang.IllegalArgumentException: Source path does not exist: /tmp/test
	at io.kestra.plugin.fs.local.List.run(List.java:76)
	at io.kestra.plugin.fs.local.Trigger.evaluate(Trigger.java:103)
	at io.kestra.core.runners.WorkerTriggerCallable.doCall(WorkerTriggerCallable.java:25)
	at io.kestra.core.runners.AbstractWorkerCallable.call(AbstractWorkerCallable.java:63)
	at io.kestra.core.runners.WorkerSecurityService.callInSecurityContext(WorkerSecurityService.java:10)
	at io.kestra.core.runners.Worker.lambda$callJob$19(Worker.java:869)
	at io.kestra.core.trace.NoopTracer.inCurrentContext(NoopTracer.java:15)
	at io.kestra.core.runners.Worker.callJob(Worker.java:865)
	at io.kestra.core.runners.Worker.lambda$handleTrigger$16(Worker.java:582)
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:141)
	at io.kestra.core.runners.Worker.handleTrigger(Worker.java:560)
	at io.kestra.core.runners.Worker.lambda$run$8(Worker.java:281)
	at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

i try with `from: "/tmp/test/"` and `from: "/tmp/test"` ==> same issue

Attempt:

I would like to keep my `from` folder and only move files that are inside the folder.

### Environment

- Kestra Version: develop
- Docker

### PR DESCRIPTION
**Pull request by Malaydewangan09**
fixes #208

### CODE REVIEW

File: src/main/java/io/kestra/plugin/fs/local/Downloads.java [hunk 1]
```diff
@@ -103,32 +103,47 @@ public class Downloads extends AbstractLocalTask implements RunnableTask<Downloa
     private Property<Boolean> recursive = Property.ofValue(false);
 
     static void performAction(
-        String from,
+        java.util.List<File> files,
         Action action,
         Property<String> moveDirectory,
         RunContext runContext) throws Exception {
         if (action == Action.DELETE) {
```
Comment (fdelbrayelle) [inline src/main/java/io/kestra/plugin/fs/local/Downloads.java:110]: Use a switch instead?

File: src/main/java/io/kestra/plugin/fs/local/Downloads.java [hunk 2]
```diff
@@ -103,32 +103,47 @@ public class Downloads extends AbstractLocalTask implements RunnableTask<Downloa
...
 
-            Move move = Move.builder()
-                .id(Move.class.getSimpleName())
-                .type(Move.class.getName())
-                .from(Property.ofValue(from))
-                .to(moveDirectory)
-                .overwrite(Property.ofValue(true))
-                .build();
-            move.run(runContext);
+            String renderedMoveDirectory = runContext.render(moveDirectory).as(String.class).orElseThrow();
```
Comment (fdelbrayelle) [inline src/main/java/io/kestra/plugin/fs/local/Downloads.java:126]:
```suggestion
            String rMoveDirectory = runContext.render(moveDirectory).as(String.class).orElseThrow();
```

**Review by fdelbrayelle — APPROVED** [review]
