### PR TITLE
fix/doc-sftp-key-file-pem-format

### LINKED ISSUE #66: Document that our implementation of FTP (JSCH) doesn't support non-PEM format
### Issue description

See https://stackoverflow.com/questions/53134212/invalid-privatekey-when-using-jsch

### PR DESCRIPTION
**Pull request by brian-mulier-p**
closes #66

### CODE REVIEW

**Review by Skraye — APPROVED** [review]
LGTM

File: src/main/java/io/kestra/plugin/fs/sftp/SftpInterface.java [hunk 1]
```diff
@@ -5,7 +5,8 @@
 
 public interface SftpInterface {
     @Schema(
-        title = "Private keyfile to login on the source server with ssh"
+        title = "Private keyfile to login on the source server with ssh, must be in PEM format",
```
Comment (anna-geller) [inline src/main/java/io/kestra/plugin/fs/sftp/SftpInterface.java:8]:
```suggestion
        title = "Private keyfile in the PEM file format to connect to a remote server using SSH",
```

**Review by anna-geller — APPROVED** [review]
thx, just a tiny nitpick
