### PR TITLE
fix(ftp): remove redundant regex filter after mapping to File

### LINKED ISSUE #109: Standard regex fails with white space
### Expected Behavior

_No response_

### Actual Behaviour

The following regex `.*test Test_nbs_issuers_.+.csv` should match on this string "test Test_nbs_issuers_YYYYMMDD.csv" but the white space seems to cause an issue using the `regEx` property.

```
id: regex
namespace: dev

tasks:
  - id: fs
    host: localhost
    port: 21
    username: foo
    password: pass
    type: io.kestra.plugin.fs.ftp.List
    from: "/folder"
    regExp: .*test Test_nbs_issuers_.+.csv
 ```

### Steps To Reproduce

_No response_

### Environment Information

- Kestra Version:
- Plugin version: 
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

### Example flow

_No response_

### PR DESCRIPTION
**Pull request by Malaydewangan09**
closes #109

### CODE REVIEW

File: src/main/java/io/kestra/plugin/fs/vfs/VfsService.java [hunk 1]
```diff
@@ -113,7 +113,6 @@ public boolean includeFile(FileSelectInfo file) throws Exception {
 
             java.util.List<File> list = Stream.of(children)
                 .map(throwFunction(r -> File.of((AbstractFileObject<?>) r)))
-                .filter(r -> regExp == null || r.getPath().toString().matches(regExp))
```
Comment (fdelbrayelle) [inline src/main/java/io/kestra/plugin/fs/vfs/VfsService.java:116]: Is there a unit test to check it's fine?

Comment (Malaydewangan09) [reply src/main/java/io/kestra/plugin/fs/vfs/VfsService.java:116]: There are regex tests already so it should be.
Or Shall i add a unit test based on reproducer given in issue?

Comment (fdelbrayelle) [reply src/main/java/io/kestra/plugin/fs/vfs/VfsService.java:116]: Yes for that kind of update always please
